### PR TITLE
Add AutoUpdate feature

### PR DESCRIPTION
**Pull request by colas31**
Add an autoUpdate feature as in the VSCode core.

### CODE REVIEW

**Comment by colas31** [comment]
Thanks @joelspadin-garmin  for the quick review, I let you merge it :)

**Comment by colas31** [comment]
@joelspadin-garmin ,  I’m sorry to bother you but I have to provide some visibility to my management and mainly a date when the feature could be available in a next version of the extension.
It includes also this feature: https://github.com/joelspadin-garmin/vscode-private-extension-manager/pull/61 

Thanks in advance, 
Best regards

**Comment by joelspadin-garmin** [comment]
I'm sorry. I won't be able to provide you with a date when this will be available. This is a side project for me, and I currently have higher priority work that I must focus on, so I do not know when I will have time to test these changes and release them.

**Comment by joelspadin-garmin** [comment]
Verified it works for me as well. Thanks!

**Pull request merged**
